---
title: "Flu_vaccination"
output: 
html_document:
      toc: yes
      theme: cerulean
---

          
```{r setup, include=FALSE}
	knitr::opts_chunk$set(echo = TRUE, warning = FALSE, tidy=TRUE, collapse=TRUE)
```

## figure 2a-c

```{}


```

## figure 2d

```{r}

library(mixOmics)
load('C:/Users/hui/Desktop/mixomics/mixomcs4.Rdata')

X <- mixomics4
Y= as.factor(sub_titer1$group)

MyResult.diablo <- block.splsda(X, Y)
plotDiablo(MyResult.diablo, ncomp = 1)

list.keepX <- list(species = 5, bolite = 5, cytokine = 5, pathway = 5)
MyResult.diablo <- block.splsda(X, Y, keepX=list.keepX)

Myauc.diablo <- auroc(MyResult.diablo, roc.block = c("species", "pathway", "bolite", "cytokine")  , roc.comp = 1)

graph.species <- Myauc.diablo[["graph.species"]][["comp1"]][["data"]]
graph.pathway <- Myauc.diablo[["graph.pathway"]][["comp1"]][["data"]]
graph.bolite <- Myauc.diablo[["graph.bolite"]][["comp1"]][["data"]]
graph.cytokine <- Myauc.diablo[["graph.cytokine"]][["comp1"]][["data"]]
graph.species$omics <- "species: AUC=0.875" 
graph.pathway$omics <- "pathway: AUC=0.844"
graph.bolite$omics <- "bolite: AUC=0.806"
graph.cytokine$omics <- "cytokine: AUC=0.675"
plotdata <- rbind(graph.cytokine, graph.bolite, graph.pathway, graph.species)
plotdata$omics <- factor(plotdata$omics, levels = c("species: AUC=0.875","pathway: AUC=0.844", "bolite: AUC=0.806", "cytokine: AUC=0.675"), ordered=TRUE)
ggplot(plotdata) + 
    geom_line(aes(x = Specificity, y = Sensitivity, color = omics), size=2) + 
    geom_abline(a=0, b=1, col="grey",lwd=1,lty=2)+
    scale_colour_manual(values=c("#9932cc", "#999900", "#90ee90", "#009999")) +
    theme(plot.title = element_text(face = 'bold',size=15))+
    theme_bw()+ 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14), legend.text=element_text(size=12)) + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    theme(title=element_text(size=14,color="#4F4F4F"))+
    labs(x = "Specificity(%)", y = "Sensitivity(%)")+
    theme(legend.position = c(0.7, 0.25))
```