---
title: "Influenza vaccination has a greater impact on the URT microbiota than the gut microbiota"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(microbiome)
library(phyloseq)
library(vegan)
library(ggplot2)
library(ggpubr)
library(pheatmap)
library(Matrix)
library(car)
library(igraph)
library(RCy3)
library(patchwork)

load('C:/Users/hui/Desktop/TIV16S2020.lihui/processing.data/physeq.tiv16sall.Rdata')
physeq<- physeq.tiv16sall
titer<- read.csv("C:/Users/hui/Desktop/TIV16S2020.lihui/processing.data/meta_immune_data.csv",header = T, sep = ',',row.names = 1)

physeq.tib<- subset_samples(physeq, type=="oroph"&national=="tibetan" & grade !="grade_19" & stage %in% c("stage1", "stage3", "stage4", "stage5"))
physeq.fp<-  prune_taxa(taxa_sums(physeq.tib) > 0, physeq.tib)

fp.sh <- plot_richness(physeq.fp, "stage", measures= "Shannon")
shannon.oroph <- fp.sh$data$value

titer2 <- titer[as.character(fp.sh$data$student_id),]
oroph.data<- cbind(fp.sh$data[,c(3,5,6)], shannon.oroph, titer2)

oroph.data13<- subset(oroph.data, stage %in% c("stage1", "stage3") & diff_H1N1 >= 0)
oroph.data13.t<- subset(oroph.data13, student_id %in% as.character(intersect(subset(oroph.data13, stage=="stage1")$student_id, subset(oroph.data13, stage=="stage3")$student_id)))
shannon.change <- subset(oroph.data13.t, stage == "stage3")$shannon.oroph - subset(oroph.data13.t, stage == "stage1")$shannon.oroph

data1 <- cbind(shannon.change, subset(oroph.data13.t, stage == "stage1"))
data1$type <- "URT"
data1 <- data1[, c("shannon.change", "student_id", "h1n1_serostatus", "h1n1_pre_group", "type")]

physeq.tib<- subset_samples(physeq, type=="fecal"&national=="tibetan" & grade !="grade_19" & stage %in% c("stage1", "stage3", "stage4", "stage5"))
physeq.fp<-  prune_taxa(taxa_sums(physeq.tib) > 0, physeq.tib)

fp.sh <- plot_richness(physeq.fp, "stage", measures= "Shannon")
shannon.fecal <- fp.sh$data$value

titer2 <- titer[as.character(fp.sh$data$student_id),]
fecal.data<- cbind(fp.sh$data[,c(3,5,6)], shannon.fecal, titer2)

fecal.data13<- subset(fecal.data, stage %in% c("stage1", "stage3") & diff_H1N1 >= 0)
fecal.data13.t<- subset(fecal.data13, student_id %in% as.character(intersect(subset(fecal.data13, stage=="stage1")$student_id, subset(fecal.data13, stage=="stage3")$student_id)))
shannon.change <- subset(fecal.data13.t, stage == "stage3")$shannon.fecal - subset(fecal.data13.t, stage == "stage1")$shannon.fecal

data2 <- cbind(shannon.change, subset(fecal.data13.t, stage == "stage1"))
data2$type <- "Gut"
data2 <- data2[, c("shannon.change", "student_id", "h1n1_serostatus", "h1n1_pre_group", "type")]
data.all <- rbind(data1, data2)

my_comparisons <- list(c("Negative", "Positive"))
ggplot(data.all, aes(x=h1n1_serostatus,  y=shannon.change), shape=8 ) +
    geom_boxplot(aes(x=h1n1_serostatus, fill=h1n1_serostatus), notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(aes(x=h1n1_serostatus), fun.y=mean, geom="point", color="white") +
    geom_jitter(aes(x=h1n1_serostatus), width=0.2, height=0, size=2) +
    geom_hline(yintercept = 0, color = 'red', size = 0.4, linetype="dashed") +
    scale_fill_manual(values=c("#386cb0", "#f0027f"))+
    theme(axis.title.x =element_blank())+
    theme_bw()+ 
    theme(axis.text.x = element_text(size=12),axis.text.y = element_text(size=12)) + 
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    theme(title=element_text(size=16))+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(axis.title.x =element_blank())+
    stat_compare_means(comparisons = my_comparisons,  paired = FALSE, color="black")+
    labs(title = "TIV Response", y = "Changes of Shannon-Index")+
    facet_wrap(.~type,scales="free", nrow=1)+
    theme(strip.text = element_text(colour = 'black', face = 'bold', size = rel(1.2)), strip.background = element_rect(fill = 'white', colour = 'black', size = rel(2), linetype = 1))

physeq.tib<- subset_samples(physeq, type %in% c("oroph", "fecal") & national=="tibetan" & grade =="grade_18" & stage %in% c("stage1", "stage3", "stage4", "stage5"))
physeq.fp<-  prune_taxa(taxa_sums(physeq.tib) > 0, physeq.tib)
fp.sh <- plot_richness(physeq.fp, "stage", measures= "Shannon")
freq <- as.data.frame(table(fp.sh$data$student_id))
data1345 <- subset(fp.sh$data, student_id %in% freq$Var1[which(freq$Freq == 8)])

col4<- c("#003399","#CC0033", "#1F6F43", "#FF6600")
my_comparisons <- list(c("stage1", "stage3"), c("stage4", "stage5"))
ggplot(data1345, aes(x=stage,  y=value), shape=8 ) +
    geom_boxplot(aes(x=stage, fill=stage), notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(aes(x=stage), fun.y=mean, geom="point", color="white") +
    geom_jitter(aes(x=stage), width=0.1, height=0, size=2) +
    scale_fill_manual(values=col4)+
    theme(axis.title.x =element_blank())+
    theme_bw()+ 
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    theme(title=element_text(size=16))+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(axis.title.x =element_blank())+
    stat_compare_means(comparisons = my_comparisons,  paired = TRUE, color="black") +
    scale_x_discrete(breaks=c("stage1", "stage3", "stage4", "stage5"), labels=c("Pre-TIV2018", "Post-TIV2018", "Pre-TIV2019", "Post-TIV2019"))+
    facet_wrap(.~type,scales="free", nrow=1)+
    theme(strip.text = element_text(colour = 'black', face = 'bold', size = rel(1.2)), strip.background = element_rect(fill = 'white', colour = 'black', size = rel(2), linetype = 1))+
    labs(y = "Shannon-Index")


col13<- c("#003399", "#CC0033")

physeq.tib<- subset_samples(physeq, type =="fecal" & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])


physeq.tib<- subset_samples(physeq, type =="fecal" & national=="tibetan" & grade %in% c("grade_16", "grade_17") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

physeq.tib<- subset_samples(physeq, type =="fecal" & national=="tibetan" & grade %in% c("grade_18", "grade_17") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

physeq.tib<- subset_samples(physeq, type =="fecal" & national=="tibetan" & grade %in% c("grade_19") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

physeq.tib<- subset_samples(physeq, type =="oroph" & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

physeq.tib<- subset_samples(physeq, type =="oroph" & national=="tibetan" & grade %in% c("grade_16", "grade_17") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

physeq.tib<- subset_samples(physeq, type =="oroph" & national=="tibetan" & grade %in% c("grade_18", "grade_17") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

physeq.tib<- subset_samples(physeq, type =="oroph" & national=="tibetan" & grade %in% c("grade_19") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)
knitr::kable(adon.results[["aov.tab"]])

####
col13<- c("#003399", "#CC0033")
col45<- c("#1F6F43", "#FF6600")

physeq.tib<- subset_samples(physeq, type =="fecal" & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)

GP.ord <- ordinate(physeq.tib, "PCoA", "bray")
data1<- plot_ordination(physeq.tib, GP.ord, type="samples", color="stage", shape="grade")
data.all <- data1$data
fecal18.13<- ggscatter(data.all, x= "Axis.1", y = "Axis.2", 
          color = "stage", palette = col13,
          size = 3, 
          ellipse = TRUE, 
          mean.point = FALSE, 
          star.plot = FALSE, 
          ellipse.level = 0.8,  
          ggtheme = theme_minimal()) +
  xlab(data1[["labels"]][["x"]]) + ylab(data1[["labels"]][["y"]])+
    theme(panel.grid = element_line(color = 'gray', linetype = 2, size = 0.1), panel.background = element_rect(color = 'black', fill = 'transparent'), legend.key = element_rect(fill = 'transparent')) + #去掉背景框
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) + 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
    labs(title="Fecal microbiota & TIV18")+
    theme(title=element_text(size=14,color="#4F4F4F"))+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(legend.title = element_blank(),legend.text = element_text(colour="#4F4F4F", size = 14))+
    annotate("text",x=-0.25,y=0.45,parse=TRUE,size=4,label=paste('Adonis-P:',adon.results$aov.tab$`Pr(>F)`[1]),family="serif",fontface="italic",colour="black")+
    annotate("text",x=-0.25,y=0.4,parse=TRUE,size=4,label=paste("R2:", adon.results$aov.tab$`R2`[1]),family="serif",fontface="italic",colour="black")+
    theme(legend.position="none")


physeq.tib<- subset_samples(physeq, type =="fecal" & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)

GP.ord <- ordinate(physeq.tib, "PCoA", "bray")
data1<- plot_ordination(physeq.tib, GP.ord, type="samples", color="stage", shape="grade")
data.all <- data1$data
fecal18.45<- ggscatter(data.all, x= "Axis.1", y = "Axis.2", 
          color = "stage", palette = col45,
          size = 3, 
          ellipse = TRUE, 
          mean.point = FALSE, 
          star.plot = FALSE, 
          ellipse.level = 0.8,  
          ggtheme = theme_minimal()) +
  xlab(data1[["labels"]][["x"]]) + ylab(data1[["labels"]][["y"]])+
    theme(panel.grid = element_line(color = 'gray', linetype = 2, size = 0.1), panel.background = element_rect(color = 'black', fill = 'transparent'), legend.key = element_rect(fill = 'transparent')) + #去掉背景框
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) + 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
    labs(title="Fecal microbiota & TIV19")+
    theme(title=element_text(size=14,color="#4F4F4F"))+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(legend.title = element_blank(),legend.text = element_text(colour="#4F4F4F", size = 14))+
    annotate("text",x=-0.25,y=0.45,parse=TRUE,size=4,label=paste('Adonis-P:',adon.results$aov.tab$`Pr(>F)`[1]),family="serif",fontface="italic",colour="black")+
    annotate("text",x=-0.25,y=0.4,parse=TRUE,size=4,label=paste("R2:", adon.results$aov.tab$`R2`[1]),family="serif",fontface="italic",colour="black")+
    theme(legend.position="none")



physeq.tib<- subset_samples(physeq, type =="oroph" & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)

GP.ord <- ordinate(physeq.tib, "PCoA", "bray")
data1<- plot_ordination(physeq.tib, GP.ord, type="samples", color="stage", shape="grade")
data.all <- data1$data
oroph18.13<- ggscatter(data.all, x= "Axis.1", y = "Axis.2", 
          color = "stage", palette = col13,
          size = 3, 
          ellipse = TRUE, 
          mean.point = FALSE, 
          star.plot = FALSE, 
          ellipse.level = 0.8, 
          ggtheme = theme_minimal()) +
  xlab(data1[["labels"]][["x"]]) + ylab(data1[["labels"]][["y"]])+
    theme(panel.grid = element_line(color = 'gray', linetype = 2, size = 0.1), panel.background = element_rect(color = 'black', fill = 'transparent'), legend.key = element_rect(fill = 'transparent')) + #去掉背景框
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) + 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
    labs(title="Oroph microbiota & TIV18 ")+
    theme(title=element_text(size=14,color="#4F4F4F"))+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(legend.title = element_blank(),legend.text = element_text(colour="#4F4F4F", size = 14))+
   annotate("text",x=-0.3,y=0.45,parse=TRUE,size=4,label=paste('Adonis-P:',adon.results$aov.tab$`Pr(>F)`[1]),family="serif",fontface="italic",colour="black")+
    annotate("text",x=-0.3,y=0.4,parse=TRUE,size=4,label=paste("R2:", adon.results$aov.tab$`R2`[1]),family="serif",fontface="italic",colour="black")+
    theme(legend.position="none")


physeq.tib<- subset_samples(physeq, type =="oroph" & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)
dis_bray.f<- phyloseq::distance(physeq.tib, "bray")
set.seed(002)
adon.results<-adonis(dis_bray.f~ meta$stage, perm=999)


GP.ord <- ordinate(physeq.tib, "PCoA", "bray")
data1<- plot_ordination(physeq.tib, GP.ord, type="samples", color="stage", shape="grade")
data.all <- data1$data
oroph18.45<- ggscatter(data.all, x= "Axis.1", y = "Axis.2", 
          color = "stage", palette = col45,
          size = 3, 
          ellipse = TRUE, 
          mean.point = FALSE, 
          star.plot = FALSE, 
          ellipse.level = 0.8,  
          ggtheme = theme_minimal()) +
  xlab(data1[["labels"]][["x"]]) + ylab(data1[["labels"]][["y"]])+
    theme(panel.grid = element_line(color = 'gray', linetype = 2, size = 0.1), panel.background = element_rect(color = 'black', fill = 'transparent'), legend.key = element_rect(fill = 'transparent')) + #去掉背景框
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) + 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
    labs(title="Oroph microbiota & TIV19 ")+
    theme(title=element_text(size=14,color="#4F4F4F"))+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(legend.title = element_blank(),legend.text = element_text(colour="#4F4F4F", size = 14))+
    annotate("text",x=-0.3,y=0.45,parse=TRUE,size=4,label=paste('Adonis-P:',adon.results$aov.tab$`Pr(>F)`[1]),family="serif",fontface="italic",colour="black")+
    annotate("text",x=-0.3,y=0.4,parse=TRUE,size=4,label=paste("R2:", adon.results$aov.tab$`R2`[1]),family="serif",fontface="italic",colour="black")+
    theme(legend.position="none")

(fecal18.13 | fecal18.45) / (oroph18.13 | oroph18.45)

```


