---
title: "URT microbes are enriched in the gut and interact with the gut microbiota"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r cars}
load('C:/Users/hui/Desktop/TIV16S2020.lihui/processing.data/physeq.tiv16sall.Rdata')
physeq<- physeq.tiv16sall
titer2<- read.csv("C:/Users/hui/Desktop/TIV16S2020.lihui/processing.data/meta_immune_data.csv",header = T, sep = ',')
titer2018 <- subset(titer2, Grade %in% c("G_2018") & h1n1_mix_group == "NP")

  student_id<- titer2018$id
  physeq.tib<- subset_samples(physeq, type %in% c("fecal", "oroph") & national=="tibetan" & grade == "grade_18" & stage %in% c("stage1", "stage3", "stage4", "stage5"))
    physeq.tib.p<-  prune_taxa(taxa_sums(physeq.tib) > 0, physeq.tib)
  sample_data(physeq.tib.p)$human <- get_variable(physeq.tib.p, "student_id") %in% student_id
  sub_physeq.tib.p<- subset_samples(physeq.tib.p, human=="TRUE")
  physeq.fo<-  prune_taxa(taxa_sums(sub_physeq.tib.p) > 0, sub_physeq.tib.p)

unifrac.fo<- phyloseq::distance(physeq.fo, "unifrac")
dis.fo<- as.matrix(unifrac.fo)

dis.fo1<- diag(dis.fo[c(1:25), c(101:125)])
dis.fo3<- diag(dis.fo[c(26:50), c(126:150)])
dis.fo4<- diag(dis.fo[c(51:75), c(151:175)])
dis.fo5<- diag(dis.fo[c(76:100), c(176:200)])
data.dis.fo<- cbind(dis.fo1, dis.fo3, dis.fo4, dis.fo5)
shape.data.dis.fo <- melt(data.dis.fo)

my_comparisons<- list(c("dis.fo1", "dis.fo3"),  c("dis.fo4", "dis.fo5"))


ggplot(data=shape.data.dis.fo, aes(x=Var2, y=value, fill =Var2))+
    geom_boxplot(notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(fun.y=mean, geom="point", color="white") +
    geom_jitter(width=0.2, size=2)+
    scale_fill_manual(values=col4)+
    theme_bw()+
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + #不显示网格线
    theme(legend.title = element_blank())+ # 不显示图例的标题
    theme(legend.position='none')+
    scale_x_discrete(breaks=c("dis.fo1", "dis.fo3", "dis.fo4", "dis.fo5"), labels=c("Pre-TIV2018", "Post-TIV2018", "Pre-TIV2019", "Post-TIV2019"))+
    theme(axis.title.x =element_blank())+
    theme(title=element_text(size=18))+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(comparisons = my_comparisons, paired = TRUE, color="black")+
    labs(y="unweighted UniFrac distances") 


col13<- c("#003399", "#CC0033")
col45<- c("#1F6F43", "#FF6600")

physeq.tib<- subset_samples(physeq, type %in% c("fecal", "oroph") & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage1", "stage3"))
meta <- meta(physeq.tib)


GP.ord <- ordinate(physeq.tib, "PCoA", "unifrac")
data1<- plot_ordination(physeq.tib, GP.ord, type="samples", color="stage", shape="grade")
data.all <- data1$data

po2<- ggscatter(data.all, x= "Axis.1", y = "Axis.2", 
          color = "stage", palette = col13, shape="type",
          size = 3, 
          ellipse = FALSE, 
          mean.point = FALSE, 
          star.plot = FALSE, 
          ellipse.level = 0.8,  
          ggtheme = theme_minimal()) +
    xlab(data1[["labels"]][["x"]]) + ylab(data1[["labels"]][["y"]])+
    theme(panel.grid = element_line(color = 'gray', linetype = 2, size = 0.1), panel.background = element_rect(color = 'black', fill = 'transparent'), legend.key = element_rect(fill = 'transparent')) + #去掉背景框
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) + 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
    theme(title=element_text(size=14,color="#4F4F4F"))+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(legend.title = element_blank(),legend.text = element_text(colour="#4F4F4F", size = 14))+
    theme(legend.position="none")

po1 <- ggplot(data.all, aes(y=type,  x=Axis.1), shape=8 ) +
    geom_boxplot(aes(y=type, fill=stage), notch=FALSE, alpha=0.7, outlier.fill = "white") +
    scale_fill_manual(values=col4)+
    theme(axis.title.x =element_blank())+
    theme_bw()+ 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    theme(title=element_text(size=16))+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(axis.title.x =element_blank())
 


physeq.tib<- subset_samples(physeq, type %in% c("fecal", "oroph") & national=="tibetan" & grade %in% c("grade_18") & stage %in% c("stage4", "stage5"))
meta <- meta(physeq.tib)


GP.ord <- ordinate(physeq.tib, "PCoA", "unifrac")
data1<- plot_ordination(physeq.tib, GP.ord, type="samples", color="stage", shape="grade")
data.all <- data1$data

po4<- ggscatter(data.all, x= "Axis.1", y = "Axis.2", 
          color = "stage", palette = col45, shape="type",
          size = 3, 
          ellipse = FALSE, 
          mean.point = FALSE, 
          star.plot = FALSE, 
          ellipse.level = 0.8,  
          ggtheme = theme_minimal()) +
    xlab(data1[["labels"]][["x"]]) + ylab(data1[["labels"]][["y"]])+
    theme(panel.grid = element_line(color = 'gray', linetype = 2, size = 0.1), panel.background = element_rect(color = 'black', fill = 'transparent'), legend.key = element_rect(fill = 'transparent')) + #去掉背景框
    geom_vline(xintercept = 0, color = 'gray', size = 0.4) + 
    geom_hline(yintercept = 0, color = 'gray', size = 0.4) + 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) + 
    theme(title=element_text(size=14,color="#4F4F4F"))+
    theme(plot.title = element_text(hjust = 0.5))+ 
    theme(legend.title = element_blank(),legend.text = element_text(colour="#4F4F4F", size = 14))+
    theme(legend.position="none")

po3 <- ggplot(data.all, aes(y=type,  x=Axis.1), shape=8 ) +
    geom_boxplot(aes(y=type, fill=stage), notch=FALSE, alpha=0.7, outlier.fill = "white") +
    scale_fill_manual(values=col4)+
    theme(axis.title.x =element_blank())+
    theme_bw()+ 
    theme(axis.text.x = element_text(size=14),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    theme(title=element_text(size=16))+
    theme(plot.title = element_text(hjust = 0.5))+
    theme(axis.title.x =element_blank())

(po1+ po2 + plot_layout(ncol = 1, heights = c(1, 3))) | (po3+ po4 + plot_layout(ncol = 1, heights = c(1, 3))) 


sourcesink<- read.csv("C:/Users/hui/Desktop/TIV16S2020.lihui/output.data/FEAST1/sourcesink.csv",header = T, sep = ',')
data.ss<- subset(sourcesink, type=="fecal")

my_comparisons<- list(c("stage1", "stage3"), c("stage4", "stage5"))

ggplot(data=data.ss, aes(x=group, y=source, fill =group))+
    geom_boxplot(notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(fun.y=mean, geom="point", color="white") +
    geom_jitter(width=0.2, size=2)+
    scale_fill_manual(values=col4)+
    theme_bw()+
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + #不显示网格线
    theme(legend.title = element_blank())+ # 不显示图例的标题
    theme(legend.position='none')+
    scale_x_discrete(breaks=c("stage1", "stage3", "stage4", "stage5"), labels=c("pre-2018", "post-2018", "pre-2019", "post-2019"))+
    theme(axis.title.x =element_blank())+
    theme(title=element_text(size=18))+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(comparisons = my_comparisons,  paired = FALSE, color="black")+
    labs(y="Proportion from oroph to fecal")

genus<- read.csv('C:/Users/hui/Desktop/TIV16S2020.lihui/all.genus.csv',header = T, sep = ',',row.names = 1)

meta <- meta(physeq)
meta$groups <- paste(meta$grade, meta$stage)

fecal <- subset(meta, grade=="grade_18"&stage != "stage2" & type=="fecal" & national=="tibetan")
genus.fecal <- genus[,rownames(fecal)]
f<-function(x) sum(x!=0)
gf <- apply(t(genus.fecal),2,f)/length(colnames(genus.fecal))

meta <- meta(physeq)
meta$groups <- paste(meta$grade, meta$stage)

oroph <- subset(meta, grade=="grade_18"&stage != "stage2" & type=="oroph" & national=="tibetan")
genus.oroph <- genus[,rownames(oroph)]
f<-function(x) sum(x!=0)
go <- apply(t(genus.oroph),2,f)/length(colnames(genus.oroph))

data.lda<- read.csv("C:/Users/hui/Desktop/plot/test1345.csv",header = T, sep = ',',row.names = 1)
gfo <- cbind(gf, go)
gfo1 <- gfo[unique(data.lda$genus),]
gfo1 <- as.data.frame(gfo1)

col <- c("#e8e9a1", "#e6b566", "#e5707e")

data.lda$genus <- factor(data.lda$genus, levels = rev(rownames(gfo1)[order(gfo1$go)]))
data.lda$stage <- factor(data.lda$stage, levels = (c("TIV2019-post", "TIV2019-pre", "TIV2018-post", "TIV2018-pre")))
data.ld <- data.lda[!duplicated(data.lda$genus),]
col1 <- subset(data.ld, genus %in% rownames(gfo1))
rownames(col1) <- col1$genus
col2 <- col1[rev(rownames(gfo1)[order(gfo1$go)]),]

p1 <- ggplot(data.lda, aes(genus,stage,fill=p)) +
    geom_point(aes(size=LDA), shape=21)+
    scale_fill_gradient(low = "black", high = "white")+
    theme_bw()+
    background_grid(major = "xy", minor = "none")+ 
    theme(axis.text.y = element_text(size=12))+
    theme(axis.text.x = element_text(color= col2$call, angle = 40, hjust = 0, vjust=1))+ 
    scale_x_discrete(position = "top")+
    geom_hline(yintercept=2.5)

gfo2 <- as.matrix(gfo1)
gfo2 <- gfo2[rev(rownames(gfo1)[order(gfo1$go)]),]
p2 <- pheatmap(t(gfo2),  cluster_cols = FALSE, cluster_rows = FALSE)

s13 <- subset(meta, grade=="grade_18"&stage %in% c("stage1", "stage3") & type=="fecal" & national=="tibetan")
s13$Bifidobacterium <- as.numeric(genus["g_Bifidobacterium",rownames(s13)])*100

my_comparisons<- list(c("stage1", "stage3"))

ggplot(data=s13, aes(x=stage, y=Bifidobacterium, fill = stage))+
    geom_boxplot(notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(fun.y=mean, geom="point", color="white") +
    geom_jitter(width=0.2, size=2)+
    scale_fill_manual(values=col4)+
    theme_bw()+
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    scale_x_discrete(breaks=c("stage1", "stage3"), labels=c("Pre-TIV2018", "Post-TIV2018"))+
    theme(axis.title.x =element_blank())+
    theme(title=element_text(size=18))+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(comparisons = my_comparisons, paired = FALSE, color="black")+
    labs(y="Relative Aboundance %") 

strain <- read.csv("C:/Users/hui/Desktop/plot/fig4c.csv",header = T, sep = ',',row.names = 1)
freq <- as.data.frame(table(strain$student_id))
sb <- subset(strain, student_id %in% freq$Var1[which(freq$Freq == 2)])
s2 <- melt(sb[,-12])

ggplot(data=s2, aes(x=group, y=value*100, fill = group))+
    geom_boxplot(notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(fun.y=mean, geom="point", color="white") +
    geom_jitter(width=0.2, size=2)+
    scale_fill_manual(values=col4)+
    theme_bw()+
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    scale_x_discrete(breaks=c("stage1", "stage3"), labels=c("Pre-TIV2018", "Post-TIV2018"))+
    theme(axis.title.x =element_blank())+
    theme(title=element_text(size=18))+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(comparisons = my_comparisons, paired = TRUE, color="black")+
    labs(y="Relative Aboundance %")+
    facet_wrap(.~variable, scales="free", nrow=1)+
    theme(strip.text = element_text(colour = 'black', face = 'bold', size = rel(1.2)), strip.background = element_rect(fill = 'white', colour = 'black', size = rel(2), linetype = 1))+
    labs(y = "Shannon-Index")


vfar <- read.csv("C:/Users/hui/Desktop/plot/path.f13.csv",header = T, sep = ',',row.names = 1)

library(qvalue)
library(ggplot2)
library(ggrepel)

a<- t(vfar[,-1])
Pvalue<-c(rep(0,nrow(a))) 
mean<-c(rep(0,nrow(a)))
for(i in 1:nrow(a)){
    y=wilcox.test(as.numeric(a[i,1:26]),as.numeric(a[i,27:42]))
    Pvalue[i]<-y$p.value
    mean[i]<-mean(as.numeric(a[i,27:42]))/mean(as.numeric(a[i,1:26])) 
}
qvalue<- qvalue(Pvalue)$qvalue
genus.f12<-cbind(mean, Pvalue, qvalue)
genus.f12<- as.data.frame(genus.f12)
genus.f12$group<- "stage12"
genus.f12$genus<- rownames(a)
Dat<- genus.f12[-which(genus.f12$mean %in% c(0, Inf)), ]


#读取数据
Dat$log2FoldChange <- log2(Dat$mean)

Dat$threshold = factor(ifelse(Dat$Pvalue < 0.05 & abs(Dat$log2FoldChange) >= 1, ifelse(Dat$log2FoldChange>= 1 ,'Up','Down'),'NoSignifi'),levels=c('Up','Down','NoSignifi'))


ggplot(Dat,aes(x=log2FoldChange,y=-log10(Pvalue),color=threshold))+
    geom_point()+
    scale_color_manual(values=c("#00008B","#808080"))+#确定点的颜色
    theme_bw()+#修改图片背景
    theme(
        legend.title = element_blank()#不显示图例标题
    )+
    ylab('-log10 (P value)')+#修改y轴名称
    xlab('log2 (FoldChange)')+#修改x轴名称
    geom_vline(xintercept=c(-1,1),lty=3,col="black",lwd=0.5) +#添加横线|FoldChange|>2
    geom_hline(yintercept = -log10(0.05),lty=3,col="black",lwd=0.5)#添加竖线padj<0.05

p1 <- ggplot(data=vfar, aes(x=stage, y=P124.PWY..Bifidobacterium.shunt, fill = stage))+
    geom_boxplot(notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(fun.y=mean, geom="point", color="white") +
    geom_jitter(width=0.2, size=2)+
    scale_fill_manual(values=col4)+
    theme_bw()+
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    scale_x_discrete(breaks=c("stage1", "stage3"), labels=c("Pre-TIV2018", "Post-TIV2018"))+
    theme(axis.title.x =element_blank())+
    theme(title=element_text(size=18))+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(comparisons = my_comparisons, paired = FALSE, color="black")+
    labs(y="Relative Aboundance")
vfar <- read.csv("C:/Users/hui/Desktop/plot/stage13.vf.csv",header = T, sep = ',',row.names = 1)
p2 <- ggplot(data=vfar, aes(x=stage, y=ZP_02422325, fill = stage))+
    geom_boxplot(notch=FALSE, alpha=0.7, outlier.fill = "white") +
    stat_summary(fun.y=mean, geom="point", color="white") +
    geom_jitter(width=0.2, size=2)+
    scale_fill_manual(values=col4)+
    theme_bw()+
    theme(axis.text.x = element_text(size=14,angle = 20, hjust = 0.9, vjust=1),axis.text.y = element_text(size=14)) +
    theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()) + 
    theme(legend.title = element_blank())+ 
    theme(legend.position='none')+
    scale_x_discrete(breaks=c("stage1", "stage3"), labels=c("Pre-TIV2018", "Post-TIV2018"))+
    theme(axis.title.x =element_blank())+
    theme(title=element_text(size=18))+
    theme(plot.title = element_text(hjust = 0.5))+
    stat_compare_means(comparisons = my_comparisons, paired = FALSE, color="black")+
    labs(y="Relative Aboundance")
p1 | p2

```

